# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=1000']
        exclude: "notebooks"
    -   id: check-yaml
        exclude: "mkdocs.yml"
-   repo: local
    hooks:
    -   id: style
        name: style
        entry: make
        args: ["style"]
        language: system
        pass_filenames: false
-   repo: https://github.com/pycqa/pylint
    rev: v3.0.1
    hooks:
    -   id: pylint
        args:
        - --errors-only
- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
      args: [
        "tests/"
      ]
